services:
    nibynool_smpp_client.transmitter:
        class: Nibynool\SmppClientBundle\Service\SmppTransmitter
        arguments:
            - [['%nibynool_smpp_client.host%'], '%nibynool_smpp_client.port%', '%nibynool_smpp_client.socket_timeout%']
            - '%nibynool_smpp_client.login%'
            - '%nibynool_smpp_client.password%'
            - '%nibynool_smpp_client.signature%'
            - '%nibynool_smpp_client.debug%'
            - '%nibynool_smpp_client.null_terminate%'
